/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Software Factory API
 * OpenAPI spec version: development
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import axios from "axios";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

/**
 * The execution state this checkpoint proves.
 */
export type AttemptState = (typeof AttemptState)[keyof typeof AttemptState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttemptState = {
  running: "running",
  succeeded: "succeeded",
  failed: "failed",
} as const;

/**
 * Whether provider usage is available.
 */
export type AttemptUsageState = (typeof AttemptUsageState)[keyof typeof AttemptUsageState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttemptUsageState = {
  unknown: "unknown",
  measured: "measured",
} as const;

export interface Attempt {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** RFC3339 UTC terminal time; absent while running. */
  endedAt?: string;
  /** The classified terminal failure, when state is failed. */
  failureKind?: string;
  /** The provider thread identity exposed by the active execution. */
  providerThreadId?: string;
  /** The terminal provider envelope; absent while running. */
  result?: unknown;
  /** The execution state this checkpoint proves. */
  state: AttemptState;
  /** Durable partial or terminal transcript material. */
  transcript?: Transcript;
  /** Provider-reported token usage; all fields are zero while usage is unknown. */
  usage: Usage;
  /** Whether provider usage is available. */
  usageState: AttemptUsageState;
}

/**
 * The part of inputTokens served from the provider's prompt cache. Null when measured is false.
 */
export type AttemptOutputCachedInputTokens = number | null;

/**
 * RFC3339 UTC. Null until the attempt ends.
 */
export type AttemptOutputEndedAt = string | null;

/**
 * The whole input, including cachedInputTokens. Null when measured is false.
 */
export type AttemptOutputInputTokens = number | null;

/**
 * The whole output, including reasoningTokens. Null when measured is false.
 */
export type AttemptOutputOutputTokens = number | null;

/**
 * The part of outputTokens spent reasoning. Null when measured is false.
 */
export type AttemptOutputReasoningTokens = number | null;

/**
 * '', 'succeeded' or 'failed'. Empty means the attempt has not ended yet.
 */
export type AttemptOutputResult = (typeof AttemptOutputResult)[keyof typeof AttemptOutputResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttemptOutputResult = {
  "": "",
  succeeded: "succeeded",
  failed: "failed",
} as const;

export interface AttemptOutput {
  /** Which attempt of this Step this is, starting at 1. */
  attemptNo: number;
  /** The part of inputTokens served from the provider's prompt cache. Null when measured is false. */
  cachedInputTokens: AttemptOutputCachedInputTokens;
  /** The reasoning effort this attempt ran on. */
  effort: string;
  /** RFC3339 UTC. Null until the attempt ends. */
  endedAt: AttemptOutputEndedAt;
  /** Whether a transcript is stored for this attempt. */
  hasTranscript: boolean;
  /** The whole input, including cachedInputTokens. Null when measured is false. */
  inputTokens: AttemptOutputInputTokens;
  /** Whether this attempt actually ran Codex. False means it resumed a stored result: the four token fields below are null, not zero, because nothing ran to measure. */
  measured: boolean;
  /** The model this attempt ran on. */
  model: string;
  /** The whole output, including reasoningTokens. Null when measured is false. */
  outputTokens: AttemptOutputOutputTokens;
  /** The part of outputTokens spent reasoning. Null when measured is false. */
  reasoningTokens: AttemptOutputReasoningTokens;
  /** '', 'succeeded' or 'failed'. Empty means the attempt has not ended yet. */
  result: AttemptOutputResult;
  /** RFC3339 UTC. */
  startedAt: string;
}

export interface BuildOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** The build version running this API. */
  version: string;
}

export type ConsoleResponseTickets = TicketSummary[] | null;

export interface ConsoleResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  tickets: ConsoleResponseTickets;
}

/**
 * Tickets that must be done before this Ticket is ready.
 */
export type CreateTicketInputBodyBlockedBy = number[] | null;

export interface CreateTicketInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Tickets that must be done before this Ticket is ready. */
  blockedBy?: CreateTicketInputBodyBlockedBy;
  /** The Ticket's supporting detail. */
  body: string;
  /**
   * The concise title describing the Ticket work.
   * @minLength 1
   */
  title: string;
}

export interface ErrorDetail {
  /** Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
  location?: string;
  /** Error message text */
  message?: string;
  /** The value at the given location */
  value?: unknown;
}

/**
 * Optional list of individual error details
 */
export type ErrorModelErrors = ErrorDetail[] | null;

export interface ErrorModel {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** Optional list of individual error details */
  errors?: ErrorModelErrors;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
  /** Stable machine-readable reason for the error. */
  reason: string;
  /** HTTP status code */
  status?: number;
  /** A short, human-readable summary of the problem type. This value should not change between occurrences of the error. */
  title?: string;
  /** A URI reference to human-readable documentation for the error. */
  type?: string;
}

export interface MaxInFlightInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Maximum number of ticket runs the dispatcher may start at once.
   * @minimum 1
   */
  maxInFlight: number;
}

/**
 * RFC3339 UTC. Null until the Run ends.
 */
export type RunOutputEndedAt = string | null;

/**
 * '', 'auth', 'rate-limit' or 'other'.
 */
export type RunOutputFailureKind = (typeof RunOutputFailureKind)[keyof typeof RunOutputFailureKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunOutputFailureKind = {
  "": "",
  auth: "auth",
  "rate-limit": "rate-limit",
  other: "other",
} as const;

/**
 * '', 'proposed', 'blocked', 'exhausted' or 'failed'. Empty until the Run ends.
 */
export type RunOutputOutcome = (typeof RunOutputOutcome)[keyof typeof RunOutputOutcome];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunOutputOutcome = {
  "": "",
  proposed: "proposed",
  blocked: "blocked",
  exhausted: "exhausted",
  failed: "failed",
} as const;

/**
 * This Run's Steps, in pipeline order.
 */
export type RunOutputSteps = StepOutput[] | null;

export interface RunOutput {
  /** RFC3339 UTC. Null until the Run ends. */
  endedAt: RunOutputEndedAt;
  /** '', 'auth', 'rate-limit' or 'other'. */
  failureKind: RunOutputFailureKind;
  /** Temporal's run id for this Run. */
  id: string;
  /** '', 'proposed', 'blocked', 'exhausted' or 'failed'. Empty until the Run ends. */
  outcome: RunOutputOutcome;
  /** RFC3339 UTC. */
  startedAt: string;
  /** This Run's Steps, in pipeline order. */
  steps: RunOutputSteps;
  /** The Ticket this Run belongs to. */
  ticketId: number;
  /** Rolled up across this Run's Steps. */
  usage: UsageOutput;
}

export interface StateTicketInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** The lifecycle state: open, active, working, review, done, or failed. Active is owned by a target Run; working and review belong to the legacy workflow. */
  state: string;
}

/**
 * This Step's attempts, oldest first. Usually one; more than one means a machine retry, not semantic re-work.
 */
export type StepOutputAttempts = AttemptOutput[] | null;

/**
 * RFC3339 UTC. Null while its last Attempt is still running.
 */
export type StepOutputEndedAt = string | null;

/**
 * plan, implement, or review.
 */
export type StepOutputStage = (typeof StepOutputStage)[keyof typeof StepOutputStage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StepOutputStage = {
  plan: "plan",
  implement: "implement",
  review: "review",
} as const;

export interface StepOutput {
  /** This Step's attempts, oldest first. Usually one; more than one means a machine retry, not semantic re-work. */
  attempts: StepOutputAttempts;
  /** RFC3339 UTC. Null while its last Attempt is still running. */
  endedAt: StepOutputEndedAt;
  /** plan, implement, or review. */
  stage: StepOutputStage;
  /** RFC3339 UTC. Its first Attempt's start. */
  startedAt: string;
  /** Which turn of Stage this is within the Run, starting at 1 — the headline number: the model was asked to do this work again. */
  turn: number;
  /** Rolled up across this Step's Attempts. */
  usage: UsageOutput;
}

/**
 * Tickets that must be done before this Ticket is ready.
 */
export type TicketResponseBlockers = TicketSummary[] | null;

/**
 * Tickets this Ticket prevents from becoming ready.
 */
export type TicketResponseBlocks = TicketSummary[] | null;

export interface TicketResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Tickets that must be done before this Ticket is ready. */
  blockers: TicketResponseBlockers;
  /** Tickets this Ticket prevents from becoming ready. */
  blocks: TicketResponseBlocks;
  /** The Ticket's supporting detail. */
  body: string;
  /** The Ticket creation time in RFC3339 UTC. */
  createdAt: string;
  /** The Ticket identifier. */
  id: number;
  /** Whether this open Ticket has only done dependencies. */
  ready: boolean;
  /** The Ticket lifecycle state. */
  state: string;
  /** The Ticket title. */
  title: string;
  /** The Ticket's latest update time in RFC3339 UTC. */
  updatedAt: string;
}

/**
 * This Ticket's Runs, most recent first.
 */
export type TicketRunsOutputBodyRuns = RunOutput[] | null;

export interface TicketRunsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** This Ticket's Runs, most recent first. */
  runs: TicketRunsOutputBodyRuns;
}

export interface TicketSummary {
  /** The Ticket creation time in RFC3339 UTC. */
  createdAt: string;
  /** The Ticket identifier. */
  id: number;
  /** Whether this open Ticket has only done dependencies. */
  ready: boolean;
  /** The Ticket lifecycle state. */
  state: string;
  /** The Ticket title. */
  title: string;
  /** The Ticket's latest update time in RFC3339 UTC. */
  updatedAt: string;
}

/**
 * Tickets matching the requested filters.
 */
export type TicketsOutputBodyTickets = TicketSummary[] | null;

export interface TicketsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Tickets matching the requested filters. */
  tickets: TicketsOutputBodyTickets;
}

export interface Transcript {
  /** Transcript checksum, base64 encoded on the wire. */
  checksum: string;
  /** Compressed transcript bytes, base64 encoded on the wire. */
  compressedBytes: string;
  /**
   * The transcript compression codec.
   * @minLength 1
   */
  compression: string;
  /**
   * Transcript size before compression.
   * @minimum 0
   */
  uncompressedSizeBytes: number;
}

export interface Usage {
  /**
   * Input tokens served from cache.
   * @minimum 0
   */
  cachedInputTokens: number;
  /**
   * Whole input tokens, including cached input.
   * @minimum 0
   */
  inputTokens: number;
  /**
   * Whole output tokens, including reasoning.
   * @minimum 0
   */
  outputTokens: number;
  /**
   * Output tokens spent reasoning.
   * @minimum 0
   */
  reasoningTokens: number;
}

export interface UsageOutput {
  /** The part of inputTokens served from the provider's prompt cache. */
  cachedInputTokens: number;
  /** False when this total omits at least one unmeasured Attempt; render it as incomplete rather than a confident sum. */
  complete: boolean;
  /** The whole input, including cachedInputTokens. */
  inputTokens: number;
  /** The whole output, including reasoningTokens. */
  outputTokens: number;
  /** The part of outputTokens spent reasoning. */
  reasoningTokens: number;
}

export type GetV1TicketsParams = {
  /**
   * Limit results to this lifecycle state.
   */
  state?: string;
  /**
   * Limit results by derived readiness: true or false.
   */
  ready?: string;
};

/**
 * @summary Get v1 build
 */
export const getV1Build = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<BuildOutputBody>> => {
  return axios.get(`/v1/build`, options);
};

export const getGetV1BuildQueryKey = () => {
  return [`/v1/build`] as const;
};

export const getGetV1BuildQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1Build>>,
  TError = AxiosError<ErrorModel>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Build>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1BuildQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Build>>> = ({ signal }) =>
    getV1Build({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1Build>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1BuildQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Build>>>;
export type GetV1BuildQueryError = AxiosError<ErrorModel>;

export function useGetV1Build<
  TData = Awaited<ReturnType<typeof getV1Build>>,
  TError = AxiosError<ErrorModel>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Build>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Build>>,
          TError,
          Awaited<ReturnType<typeof getV1Build>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1Build<
  TData = Awaited<ReturnType<typeof getV1Build>>,
  TError = AxiosError<ErrorModel>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Build>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Build>>,
          TError,
          Awaited<ReturnType<typeof getV1Build>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1Build<
  TData = Awaited<ReturnType<typeof getV1Build>>,
  TError = AxiosError<ErrorModel>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Build>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get v1 build
 */

export function useGetV1Build<
  TData = Awaited<ReturnType<typeof getV1Build>>,
  TError = AxiosError<ErrorModel>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Build>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetV1BuildQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns the factory Tickets for the console.
 * @summary Read console snapshot
 */
export const getV1Console = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ConsoleResponse>> => {
  return axios.get(`/v1/console`, options);
};

export const getGetV1ConsoleQueryKey = () => {
  return [`/v1/console`] as const;
};

export const getGetV1ConsoleQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1Console>>,
  TError = AxiosError<ErrorModel>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Console>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1ConsoleQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Console>>> = ({ signal }) =>
    getV1Console({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1Console>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1ConsoleQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Console>>>;
export type GetV1ConsoleQueryError = AxiosError<ErrorModel>;

export function useGetV1Console<
  TData = Awaited<ReturnType<typeof getV1Console>>,
  TError = AxiosError<ErrorModel>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Console>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Console>>,
          TError,
          Awaited<ReturnType<typeof getV1Console>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1Console<
  TData = Awaited<ReturnType<typeof getV1Console>>,
  TError = AxiosError<ErrorModel>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Console>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Console>>,
          TError,
          Awaited<ReturnType<typeof getV1Console>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1Console<
  TData = Awaited<ReturnType<typeof getV1Console>>,
  TError = AxiosError<ErrorModel>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Console>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Read console snapshot
 */

export function useGetV1Console<
  TData = Awaited<ReturnType<typeof getV1Console>>,
  TError = AxiosError<ErrorModel>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Console>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetV1ConsoleQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Success means Temporal accepted the UpdateConfig signal. The dispatcher applies this configuration on its next tick; this endpoint does not poll for observable state.
 * @summary Set factory max in flight
 */
export const postV1FactoryMaxInFlight = (
  maxInFlightInputBody: NonReadonly<MaxInFlightInputBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(`/v1/factory/max-in-flight`, maxInFlightInputBody, options);
};

export const getPostV1FactoryMaxInFlightMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postV1FactoryMaxInFlight>>,
    TError,
    { data: NonReadonly<MaxInFlightInputBody> },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postV1FactoryMaxInFlight>>,
  TError,
  { data: NonReadonly<MaxInFlightInputBody> },
  TContext
> => {
  const mutationKey = ["postV1FactoryMaxInFlight"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postV1FactoryMaxInFlight>>,
    { data: NonReadonly<MaxInFlightInputBody> }
  > = (props) => {
    const { data } = props ?? {};

    return postV1FactoryMaxInFlight(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1FactoryMaxInFlightMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1FactoryMaxInFlight>>
>;
export type PostV1FactoryMaxInFlightMutationBody = NonReadonly<MaxInFlightInputBody>;
export type PostV1FactoryMaxInFlightMutationError = AxiosError<ErrorModel>;

/**
 * @summary Set factory max in flight
 */
export const usePostV1FactoryMaxInFlight = <TError = AxiosError<ErrorModel>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postV1FactoryMaxInFlight>>,
      TError,
      { data: NonReadonly<MaxInFlightInputBody> },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postV1FactoryMaxInFlight>>,
  TError,
  { data: NonReadonly<MaxInFlightInputBody> },
  TContext
> => {
  const mutationOptions = getPostV1FactoryMaxInFlightMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Success means Temporal accepted the UpdateConfig signal. The dispatcher applies this configuration on its next tick; this endpoint does not poll for observable state.
 * @summary Pause the factory
 */
export const postV1FactoryPause = (options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.post(`/v1/factory/pause`, undefined, options);
};

export const getPostV1FactoryPauseMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postV1FactoryPause>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postV1FactoryPause>>, TError, void, TContext> => {
  const mutationKey = ["postV1FactoryPause"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FactoryPause>>, void> = () => {
    return postV1FactoryPause(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1FactoryPauseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1FactoryPause>>
>;

export type PostV1FactoryPauseMutationError = AxiosError<ErrorModel>;

/**
 * @summary Pause the factory
 */
export const usePostV1FactoryPause = <TError = AxiosError<ErrorModel>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postV1FactoryPause>>,
      TError,
      void,
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postV1FactoryPause>>, TError, void, TContext> => {
  const mutationOptions = getPostV1FactoryPauseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Success means Temporal accepted the UpdateConfig signal. The dispatcher applies this configuration on its next tick; this endpoint does not poll for observable state.
 * @summary Resume the factory
 */
export const postV1FactoryResume = (options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.post(`/v1/factory/resume`, undefined, options);
};

export const getPostV1FactoryResumeMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postV1FactoryResume>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postV1FactoryResume>>, TError, void, TContext> => {
  const mutationKey = ["postV1FactoryResume"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postV1FactoryResume>>,
    void
  > = () => {
    return postV1FactoryResume(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1FactoryResumeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1FactoryResume>>
>;

export type PostV1FactoryResumeMutationError = AxiosError<ErrorModel>;

/**
 * @summary Resume the factory
 */
export const usePostV1FactoryResume = <TError = AxiosError<ErrorModel>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postV1FactoryResume>>,
      TError,
      void,
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postV1FactoryResume>>, TError, void, TContext> => {
  const mutationOptions = getPostV1FactoryResumeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Stores running provider identity or terminal execution evidence using a capability scoped to the exact Run, Step, and Agent Attempt.
 * @summary Checkpoint an active Agent Attempt
 */
export const putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint = (
  runID: string,
  stepOrdinal: number,
  attemptNo: number,
  attempt: NonReadonly<Attempt>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.put(
    `/v1/run-worker/runs/${runID}/steps/${stepOrdinal}/attempts/${attemptNo}/checkpoint`,
    attempt,
    options,
  );
};

export const getPutV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpointMutationOptions =
  <TError = AxiosError<ErrorModel>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint>
      >,
      TError,
      { runID: string; stepOrdinal: number; attemptNo: number; data: NonReadonly<Attempt> },
      TContext
    >;
    axios?: AxiosRequestConfig;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint>
    >,
    TError,
    { runID: string; stepOrdinal: number; attemptNo: number; data: NonReadonly<Attempt> },
    TContext
  > => {
    const mutationKey = [
      "putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint",
    ];
    const { mutation: mutationOptions, axios: axiosOptions } = options
      ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, axios: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint>
      >,
      { runID: string; stepOrdinal: number; attemptNo: number; data: NonReadonly<Attempt> }
    > = (props) => {
      const { runID, stepOrdinal, attemptNo, data } = props ?? {};

      return putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint(
        runID,
        stepOrdinal,
        attemptNo,
        data,
        axiosOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type PutV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpointMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint>
    >
  >;
export type PutV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpointMutationBody =
  NonReadonly<Attempt>;
export type PutV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpointMutationError =
  AxiosError<ErrorModel>;

/**
 * @summary Checkpoint an active Agent Attempt
 */
export const usePutV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint>
      >,
      TError,
      { runID: string; stepOrdinal: number; attemptNo: number; data: NonReadonly<Attempt> },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<
    ReturnType<typeof putV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpoint>
  >,
  TError,
  { runID: string; stepOrdinal: number; attemptNo: number; data: NonReadonly<Attempt> },
  TContext
> => {
  const mutationOptions =
    getPutV1RunWorkerRunsByRunIdStepsByStepOrdinalAttemptsByAttemptNoCheckpointMutationOptions(
      options,
    );

  return useMutation(mutationOptions, queryClient);
};

/**
 * Lists Tickets with optional state and derived ready filters.
 * @summary List Tickets
 */
export const getV1Tickets = (
  params?: GetV1TicketsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TicketsOutputBody>> => {
  return axios.get(`/v1/tickets`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetV1TicketsQueryKey = (params?: GetV1TicketsParams) => {
  return [`/v1/tickets`, ...(params ? [params] : [])] as const;
};

export const getGetV1TicketsQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1Tickets>>,
  TError = AxiosError<ErrorModel>,
>(
  params?: GetV1TicketsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Tickets>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1TicketsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Tickets>>> = ({ signal }) =>
    getV1Tickets(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1Tickets>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1TicketsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Tickets>>>;
export type GetV1TicketsQueryError = AxiosError<ErrorModel>;

export function useGetV1Tickets<
  TData = Awaited<ReturnType<typeof getV1Tickets>>,
  TError = AxiosError<ErrorModel>,
>(
  params: undefined | GetV1TicketsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Tickets>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Tickets>>,
          TError,
          Awaited<ReturnType<typeof getV1Tickets>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1Tickets<
  TData = Awaited<ReturnType<typeof getV1Tickets>>,
  TError = AxiosError<ErrorModel>,
>(
  params?: GetV1TicketsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Tickets>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Tickets>>,
          TError,
          Awaited<ReturnType<typeof getV1Tickets>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1Tickets<
  TData = Awaited<ReturnType<typeof getV1Tickets>>,
  TError = AxiosError<ErrorModel>,
>(
  params?: GetV1TicketsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Tickets>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List Tickets
 */

export function useGetV1Tickets<
  TData = Awaited<ReturnType<typeof getV1Tickets>>,
  TError = AxiosError<ErrorModel>,
>(
  params?: GetV1TicketsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Tickets>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetV1TicketsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Files a new open Ticket.
 * @summary Create a Ticket
 */
export const postV1Tickets = (
  createTicketInputBody: NonReadonly<CreateTicketInputBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TicketResponse>> => {
  return axios.post(`/v1/tickets`, createTicketInputBody, options);
};

export const getPostV1TicketsMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postV1Tickets>>,
    TError,
    { data: NonReadonly<CreateTicketInputBody> },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postV1Tickets>>,
  TError,
  { data: NonReadonly<CreateTicketInputBody> },
  TContext
> => {
  const mutationKey = ["postV1Tickets"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postV1Tickets>>,
    { data: NonReadonly<CreateTicketInputBody> }
  > = (props) => {
    const { data } = props ?? {};

    return postV1Tickets(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1TicketsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Tickets>>>;
export type PostV1TicketsMutationBody = NonReadonly<CreateTicketInputBody>;
export type PostV1TicketsMutationError = AxiosError<ErrorModel>;

/**
 * @summary Create a Ticket
 */
export const usePostV1Tickets = <TError = AxiosError<ErrorModel>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postV1Tickets>>,
      TError,
      { data: NonReadonly<CreateTicketInputBody> },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postV1Tickets>>,
  TError,
  { data: NonReadonly<CreateTicketInputBody> },
  TContext
> => {
  const mutationOptions = getPostV1TicketsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Returns the Ticket, both dependency directions, and derived readiness.
 * @summary Read a Ticket
 */
export const getV1TicketsByTicketId = (
  ticketID: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TicketResponse>> => {
  return axios.get(`/v1/tickets/${ticketID}`, options);
};

export const getGetV1TicketsByTicketIdQueryKey = (ticketID?: number) => {
  return [`/v1/tickets/${ticketID}`] as const;
};

export const getGetV1TicketsByTicketIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketId>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1TicketsByTicketIdQueryKey(ticketID);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1TicketsByTicketId>>> = ({ signal }) =>
    getV1TicketsByTicketId(ticketID, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!ticketID, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1TicketsByTicketIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1TicketsByTicketId>>
>;
export type GetV1TicketsByTicketIdQueryError = AxiosError<ErrorModel>;

export function useGetV1TicketsByTicketId<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
          TError,
          Awaited<ReturnType<typeof getV1TicketsByTicketId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1TicketsByTicketId<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
          TError,
          Awaited<ReturnType<typeof getV1TicketsByTicketId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1TicketsByTicketId<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketId>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Read a Ticket
 */

export function useGetV1TicketsByTicketId<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketId>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketId>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetV1TicketsByTicketIdQueryOptions(ticketID, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Removes a dependency edge when it exists.
 * @summary Remove a Ticket blocker
 */
export const deleteV1TicketsByTicketIdBlockersByBlockerTicketId = (
  ticketID: number,
  blockerTicketID: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/v1/tickets/${ticketID}/blockers/${blockerTicketID}`, options);
};

export const getDeleteV1TicketsByTicketIdBlockersByBlockerTicketIdMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteV1TicketsByTicketIdBlockersByBlockerTicketId>>,
    TError,
    { ticketID: number; blockerTicketID: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteV1TicketsByTicketIdBlockersByBlockerTicketId>>,
  TError,
  { ticketID: number; blockerTicketID: number },
  TContext
> => {
  const mutationKey = ["deleteV1TicketsByTicketIdBlockersByBlockerTicketId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteV1TicketsByTicketIdBlockersByBlockerTicketId>>,
    { ticketID: number; blockerTicketID: number }
  > = (props) => {
    const { ticketID, blockerTicketID } = props ?? {};

    return deleteV1TicketsByTicketIdBlockersByBlockerTicketId(
      ticketID,
      blockerTicketID,
      axiosOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteV1TicketsByTicketIdBlockersByBlockerTicketIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteV1TicketsByTicketIdBlockersByBlockerTicketId>>
>;

export type DeleteV1TicketsByTicketIdBlockersByBlockerTicketIdMutationError =
  AxiosError<ErrorModel>;

/**
 * @summary Remove a Ticket blocker
 */
export const useDeleteV1TicketsByTicketIdBlockersByBlockerTicketId = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteV1TicketsByTicketIdBlockersByBlockerTicketId>>,
      TError,
      { ticketID: number; blockerTicketID: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteV1TicketsByTicketIdBlockersByBlockerTicketId>>,
  TError,
  { ticketID: number; blockerTicketID: number },
  TContext
> => {
  const mutationOptions =
    getDeleteV1TicketsByTicketIdBlockersByBlockerTicketIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Records that the first Ticket is blocked by the second.
 * @summary Add a Ticket blocker
 */
export const putV1TicketsByTicketIdBlockersByBlockerTicketId = (
  ticketID: number,
  blockerTicketID: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.put(`/v1/tickets/${ticketID}/blockers/${blockerTicketID}`, undefined, options);
};

export const getPutV1TicketsByTicketIdBlockersByBlockerTicketIdMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putV1TicketsByTicketIdBlockersByBlockerTicketId>>,
    TError,
    { ticketID: number; blockerTicketID: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putV1TicketsByTicketIdBlockersByBlockerTicketId>>,
  TError,
  { ticketID: number; blockerTicketID: number },
  TContext
> => {
  const mutationKey = ["putV1TicketsByTicketIdBlockersByBlockerTicketId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putV1TicketsByTicketIdBlockersByBlockerTicketId>>,
    { ticketID: number; blockerTicketID: number }
  > = (props) => {
    const { ticketID, blockerTicketID } = props ?? {};

    return putV1TicketsByTicketIdBlockersByBlockerTicketId(ticketID, blockerTicketID, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutV1TicketsByTicketIdBlockersByBlockerTicketIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putV1TicketsByTicketIdBlockersByBlockerTicketId>>
>;

export type PutV1TicketsByTicketIdBlockersByBlockerTicketIdMutationError = AxiosError<ErrorModel>;

/**
 * @summary Add a Ticket blocker
 */
export const usePutV1TicketsByTicketIdBlockersByBlockerTicketId = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putV1TicketsByTicketIdBlockersByBlockerTicketId>>,
      TError,
      { ticketID: number; blockerTicketID: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putV1TicketsByTicketIdBlockersByBlockerTicketId>>,
  TError,
  { ticketID: number; blockerTicketID: number },
  TContext
> => {
  const mutationOptions =
    getPutV1TicketsByTicketIdBlockersByBlockerTicketIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Success means Temporal accepted cancellation of the ticket workflow. This endpoint does not wait for cleanup or database state to become observable.
 * @summary Cancel a ticket run
 */
export const postV1TicketsByTicketIdCancel = (
  ticketID: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(`/v1/tickets/${ticketID}/cancel`, undefined, options);
};

export const getPostV1TicketsByTicketIdCancelMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postV1TicketsByTicketIdCancel>>,
    TError,
    { ticketID: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postV1TicketsByTicketIdCancel>>,
  TError,
  { ticketID: number },
  TContext
> => {
  const mutationKey = ["postV1TicketsByTicketIdCancel"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postV1TicketsByTicketIdCancel>>,
    { ticketID: number }
  > = (props) => {
    const { ticketID } = props ?? {};

    return postV1TicketsByTicketIdCancel(ticketID, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1TicketsByTicketIdCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1TicketsByTicketIdCancel>>
>;

export type PostV1TicketsByTicketIdCancelMutationError = AxiosError<ErrorModel>;

/**
 * @summary Cancel a ticket run
 */
export const usePostV1TicketsByTicketIdCancel = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postV1TicketsByTicketIdCancel>>,
      TError,
      { ticketID: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postV1TicketsByTicketIdCancel>>,
  TError,
  { ticketID: number },
  TContext
> => {
  const mutationOptions = getPostV1TicketsByTicketIdCancelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Returns every Run of the Ticket, most recent first, each with its Steps and Attempts and rolled-up token usage.
 * @summary List a Ticket's Runs
 */
export const getV1TicketsByTicketIdRuns = (
  ticketID: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TicketRunsOutputBody>> => {
  return axios.get(`/v1/tickets/${ticketID}/runs`, options);
};

export const getGetV1TicketsByTicketIdRunsQueryKey = (ticketID?: number) => {
  return [`/v1/tickets/${ticketID}/runs`] as const;
};

export const getGetV1TicketsByTicketIdRunsQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1TicketsByTicketIdRunsQueryKey(ticketID);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>> = ({
    signal,
  }) => getV1TicketsByTicketIdRuns(ticketID, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!ticketID, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1TicketsByTicketIdRunsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>
>;
export type GetV1TicketsByTicketIdRunsQueryError = AxiosError<ErrorModel>;

export function useGetV1TicketsByTicketIdRuns<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
          TError,
          Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1TicketsByTicketIdRuns<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
          TError,
          Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetV1TicketsByTicketIdRuns<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List a Ticket's Runs
 */

export function useGetV1TicketsByTicketIdRuns<
  TData = Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1TicketsByTicketIdRuns>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetV1TicketsByTicketIdRunsQueryOptions(ticketID, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns the Attempt's raw JSONL event stream, decompressed, as a downloadable file.
 * @summary Download an Attempt's transcript
 */
export const listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript =
  (
    ticketID: number,
    runID: string,
    stage: "plan" | "implement" | "review",
    turn: number,
    attemptNo: number,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<string>> => {
    return axios.get(
      `/v1/tickets/${ticketID}/runs/${runID}/stages/${stage}/turns/${turn}/attempts/${attemptNo}/transcript`,
      {
        ...options,
      },
    );
  };

export const getListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscriptQueryKey =
  (
    ticketID?: number,
    runID?: string,
    stage?: "plan" | "implement" | "review",
    turn?: number,
    attemptNo?: number,
  ) => {
    return [
      `/v1/tickets/${ticketID}/runs/${runID}/stages/${stage}/turns/${turn}/attempts/${attemptNo}/transcript`,
    ] as const;
  };

export const getListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscriptQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
      >
    >,
    TError = AxiosError<ErrorModel>,
  >(
    ticketID: number,
    runID: string,
    stage: "plan" | "implement" | "review",
    turn: number,
    attemptNo: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
            >
          >,
          TError,
          TData
        >
      >;
      axios?: AxiosRequestConfig;
    },
  ) => {
    const { query: queryOptions, axios: axiosOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscriptQueryKey(
        ticketID,
        runID,
        stage,
        turn,
        attemptNo,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
        >
      >
    > = ({ signal }) =>
      listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript(
        ticketID,
        runID,
        stage,
        turn,
        attemptNo,
        { signal, ...axiosOptions },
      );

    return {
      queryKey,
      queryFn,
      enabled: !!(ticketID && runID && stage && turn && attemptNo),
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
        >
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type ListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscriptQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
      >
    >
  >;
export type ListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscriptQueryError =
  AxiosError<ErrorModel>;

export function useListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript<
  TData = Awaited<
    ReturnType<
      typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
    >
  >,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  runID: string,
  stage: "plan" | "implement" | "review",
  turn: number,
  attemptNo: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
            >
          >
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript<
  TData = Awaited<
    ReturnType<
      typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
    >
  >,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  runID: string,
  stage: "plan" | "implement" | "review",
  turn: number,
  attemptNo: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
            >
          >
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript<
  TData = Awaited<
    ReturnType<
      typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
    >
  >,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  runID: string,
  stage: "plan" | "implement" | "review",
  turn: number,
  attemptNo: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
          >
        >,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Download an Attempt's transcript
 */

export function useListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript<
  TData = Awaited<
    ReturnType<
      typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
    >
  >,
  TError = AxiosError<ErrorModel>,
>(
  ticketID: number,
  runID: string,
  stage: "plan" | "implement" | "review",
  turn: number,
  attemptNo: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof listV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscript
          >
        >,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getListV1TicketsByTicketIdRunsByRunIdStagesByStageTurnsByTurnAttemptsByAttemptNoTranscriptQueryOptions(
      ticketID,
      runID,
      stage,
      turn,
      attemptNo,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Moves a Ticket through its legal lifecycle transitions.
 * @summary Update Ticket state
 */
export const patchV1TicketsByTicketIdState = (
  ticketID: number,
  stateTicketInputBody: NonReadonly<StateTicketInputBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TicketResponse>> => {
  return axios.patch(`/v1/tickets/${ticketID}/state`, stateTicketInputBody, options);
};

export const getPatchV1TicketsByTicketIdStateMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchV1TicketsByTicketIdState>>,
    TError,
    { ticketID: number; data: NonReadonly<StateTicketInputBody> },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchV1TicketsByTicketIdState>>,
  TError,
  { ticketID: number; data: NonReadonly<StateTicketInputBody> },
  TContext
> => {
  const mutationKey = ["patchV1TicketsByTicketIdState"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchV1TicketsByTicketIdState>>,
    { ticketID: number; data: NonReadonly<StateTicketInputBody> }
  > = (props) => {
    const { ticketID, data } = props ?? {};

    return patchV1TicketsByTicketIdState(ticketID, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchV1TicketsByTicketIdStateMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchV1TicketsByTicketIdState>>
>;
export type PatchV1TicketsByTicketIdStateMutationBody = NonReadonly<StateTicketInputBody>;
export type PatchV1TicketsByTicketIdStateMutationError = AxiosError<ErrorModel>;

/**
 * @summary Update Ticket state
 */
export const usePatchV1TicketsByTicketIdState = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchV1TicketsByTicketIdState>>,
      TError,
      { ticketID: number; data: NonReadonly<StateTicketInputBody> },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchV1TicketsByTicketIdState>>,
  TError,
  { ticketID: number; data: NonReadonly<StateTicketInputBody> },
  TContext
> => {
  const mutationOptions = getPatchV1TicketsByTicketIdStateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Success means Temporal accepted an empty UpdateConfig signal that wakes the dispatcher without changing configuration. This endpoint does not poll for observable state.
 * @summary Nudge the factory
 */
export const postV1TicketsByTicketIdWork = (
  ticketID: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(`/v1/tickets/${ticketID}/work`, undefined, options);
};

export const getPostV1TicketsByTicketIdWorkMutationOptions = <
  TError = AxiosError<ErrorModel>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postV1TicketsByTicketIdWork>>,
    TError,
    { ticketID: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postV1TicketsByTicketIdWork>>,
  TError,
  { ticketID: number },
  TContext
> => {
  const mutationKey = ["postV1TicketsByTicketIdWork"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postV1TicketsByTicketIdWork>>,
    { ticketID: number }
  > = (props) => {
    const { ticketID } = props ?? {};

    return postV1TicketsByTicketIdWork(ticketID, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1TicketsByTicketIdWorkMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1TicketsByTicketIdWork>>
>;

export type PostV1TicketsByTicketIdWorkMutationError = AxiosError<ErrorModel>;

/**
 * @summary Nudge the factory
 */
export const usePostV1TicketsByTicketIdWork = <TError = AxiosError<ErrorModel>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postV1TicketsByTicketIdWork>>,
      TError,
      { ticketID: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postV1TicketsByTicketIdWork>>,
  TError,
  { ticketID: number },
  TContext
> => {
  const mutationOptions = getPostV1TicketsByTicketIdWorkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
