TS_AUTHKEY: ENC[AES256_GCM,data:ANKOjfvgo6tAfBo9VsUc4y18YdyR0Aj8+fKPycjwEiZzIMgQRzggp4HlrA4gyp2YOY0QuT6c3UE4PSpiWuU=,iv:w3PNZQqUKhErOVTu7YGUL7hIBNAth2QXOayKNg6/uvY=,tag:G9dKdYCbIxVYPGei/MPDiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WmY3QkRxVU9XaUY1WnE2
            SThCY2lMcmFtVjAzUzN3Tmx0ZmJaZGtIc2pnCll5VmExRlVPeUVYdUIrUklZZVZ2
            NTZVVHZjVkVyUml1Nk5VSHJ2b2t4OWsKLS0tIGtCdmYwZCtwSW9HOWc5ZlRFZDNh
            dUVmVWk1TktCbFgwSDR0VVpWczcrajAKIvp7fLE0yEsU99IvBAk6PZNftuT44oNW
            iw9/qBhOtexrFkFmBRbF9BsYuakhMbjx/0KW/dv/pcdnnee75Md0aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zds5tlctxmh9lse5p5cjv3vgsqxl5f0n774hculp78tdwymshd4q8vd0ew
    lastmodified: "2026-07-25T17:06:25Z"
    mac: ENC[AES256_GCM,data:eZh3zxmpE50UKjMWkX+Vy8Zlt6XURLRtY84rLfisoXP4TR8GXh6eBS5hczG8t8hQTVEU6TtazBQeGtZMAue3fSgyL4RS4tiTp06s9NjZ4KAjN7a55BRiZzIrPMA4Qay9QkrbahzjzZv6av4uHuylG6gLhhWiak77UOr9vIUNwK8=,iv:jTcGMs/NvonvK8O0/kwSQUQPgQQMJ8aUPj1Y4aqqUJ8=,tag:71iDmZoXZDgO2631Ke/i3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
