TS_AUTHKEY: ENC[AES256_GCM,data:rqSmVfzLmsr1HPuTrN69UL1LkrS/QHEcNKMqsPLxWRGGi1C/Avm7WzgYcnNSR9yirxvO+kY0LC2wxc1jnpY=,iv:qR7DQocuPpgZh4YKCIRyT0FSykPif0T8S+1QPueWnTg=,tag:NjEk4PyE1oUbp+omS+kmYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WmY3QkRxVU9XaUY1WnE2
            SThCY2lMcmFtVjAzUzN3Tmx0ZmJaZGtIc2pnCll5VmExRlVPeUVYdUIrUklZZVZ2
            NTZVVHZjVkVyUml1Nk5VSHJ2b2t4OWsKLS0tIGtCdmYwZCtwSW9HOWc5ZlRFZDNh
            dUVmVWk1TktCbFgwSDR0VVpWczcrajAKIvp7fLE0yEsU99IvBAk6PZNftuT44oNW
            iw9/qBhOtexrFkFmBRbF9BsYuakhMbjx/0KW/dv/pcdnnee75Md0aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zds5tlctxmh9lse5p5cjv3vgsqxl5f0n774hculp78tdwymshd4q8vd0ew
    lastmodified: "2026-07-25T13:32:40Z"
    mac: ENC[AES256_GCM,data:Qb6gwF0rJOvkbcwczeHqRUJMJ8OmoetXpDyzGXzmbpMjJvTutr/Yk1DqT/3Ys1mz76EAtIHZeoP67wosUYjk7/5RHPBeJ9lhxlaUvmDOBemCJQoR/Yfz5dArKpWGdAi1i7G39QE1Esw4SDWcaxgeUo45fzNqqr580P8GGLtGuX0=,iv:uNU5XL9/RMlIEQPBboVSdvkuf6eJhlRs4ByUbJf4e8U=,tag:O/cCLNj0EFLZn/jEQbdaOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
