// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration_probe.sql

package store

import (
	"context"
)

const migrationProbeExists = `-- name: MigrationProbeExists :one
SELECT EXISTS (SELECT 1 FROM migration_probe) AS exists
`

func (q *Queries) MigrationProbeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, migrationProbeExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
