package work

import (
	"fmt"
	"strings"
	"time"
)

// RunWorkerID identifies one concrete worker generation for a target Run.
type RunWorkerID string

// RunWorkerIdentity is the stable Run plus the replaceable worker generation.
// Generation starts at one and increases only after permanent worker loss.
type RunWorkerIdentity struct {
	RunID      string
	Generation int
}

// Validate rejects identities that cannot be embedded safely in Kubernetes and
// Temporal names. Run IDs are generated by Temporal; accepting only its
// lowercase UUID-shaped alphabet keeps target names deterministic and inert.
func (i RunWorkerIdentity) Validate() error {
	if i.RunID == "" {
		return fmt.Errorf("run worker identity needs a Run ID: %w", ErrInvalidRun)
	}
	if i.Generation <= 0 {
		return fmt.Errorf("run worker identity needs a positive generation: %w", ErrInvalidRun)
	}
	if len(i.RunID) > 48 || strings.Trim(i.RunID, "abcdefghijklmnopqrstuvwxyz0123456789-") != "" {
		return fmt.Errorf("run worker Run ID %q is not name-safe: %w", i.RunID, ErrInvalidRun)
	}
	return nil
}

const runWorkerTaskQueuePrefix = "software-factory-run-worker-"

// RunWorkerTaskQueue is the private queue for one concrete worker generation.
func RunWorkerTaskQueue(runID string, generation int) string {
	return fmt.Sprintf("%s%s-g%d", runWorkerTaskQueuePrefix, runID, generation)
}

// RunWorkerName is the Kubernetes name for one concrete worker generation.
func RunWorkerName(identity RunWorkerIdentity) RunWorkerID {
	return RunWorkerID(fmt.Sprintf("run-worker-%s-g%d", identity.RunID, identity.Generation))
}

// RunWorkerCredentialRevision is the complete safe result of installing a
// renewable credential. It may cross a Temporal activity boundary; the token
// itself may not.
type RunWorkerCredentialRevision struct {
	Revision  string
	ExpiresAt time.Time
}

// Validate reports whether the installed revision can be observed safely.
func (r RunWorkerCredentialRevision) Validate() error {
	if strings.TrimSpace(r.Revision) == "" {
		return fmt.Errorf("run worker credential revision is empty: %w", ErrInvalidRun)
	}
	if r.ExpiresAt.IsZero() {
		return fmt.Errorf("run worker credential expiry is empty: %w", ErrInvalidRun)
	}
	return nil
}

// RunWorkerSpec describes one target worker pod without carrying any secret.
type RunWorkerSpec struct {
	TicketNumber    int
	Identity        RunWorkerIdentity
	Image           string
	CPURequest      string
	MemoryLimit     string
	DeadlineSeconds int64
	Env             map[string]string
}

// RunWorkerSecretMaterial is handed directly from the main-control activity to
// Kubernetes. Credential's JSON refusal prevents either value from entering
// Temporal history accidentally.
type RunWorkerSecretMaterial struct {
	GitHubToken          Credential
	GitHubLogin          string
	GitHubExpiresAt      time.Time
	CheckpointCapability Credential
}

// Published environment and projected-file paths shared by the provisioner,
// image, and Run Worker composition root. Secret values never have env names.
const (
	RunWorkerIDEnv                    = "RUN_WORKER_ID"
	RunWorkerRunIDEnv                 = "RUN_ID"
	RunWorkerGenerationEnv            = "RUN_WORKER_GENERATION"
	RunWorkerTaskQueueEnv             = "RUN_WORKER_TASK_QUEUE"
	RunWorkerTemporalHostPortEnv      = "TEMPORAL_HOST_PORT"
	RunWorkerTemporalNamespaceEnv     = "TEMPORAL_NAMESPACE"
	RunWorkerBlobsURLEnv              = "BLOBS_URL"
	RunWorkerCheckpointAPIURLEnv      = "CHECKPOINT_API_URL"
	RunWorkerGitHubCredentialDir      = "/var/run/secrets/software-factory/github"
	RunWorkerGitHubTokenFile          = RunWorkerGitHubCredentialDir + "/token"
	RunWorkerGitHubLoginFile          = RunWorkerGitHubCredentialDir + "/login"
	RunWorkerGitHubRevisionFile       = RunWorkerGitHubCredentialDir + "/revision"
	RunWorkerGitHubExpiresAtFile      = RunWorkerGitHubCredentialDir + "/expires-at"
	RunWorkerCheckpointCapabilityDir  = "/var/run/secrets/software-factory/checkpoint"
	RunWorkerCheckpointCapabilityFile = RunWorkerCheckpointCapabilityDir + "/capability"
)
