// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

export interface GeneratedSchedule {
  /** Full Temporal schedule ID (`app_<feature-dir>_<localId>`) — the managed-by marker. */
  scheduleId: string;
  workflowType: string;
  cron: string;
  timezone: string | undefined;
  /** The workflow's single argument, JSON-encoded (one-arg convention). */
  argsJson: string | undefined;
  timeout: string | undefined;
  catchupWindow: string | undefined;
  source: string;
}

export const GENERATED_SCHEDULES: readonly GeneratedSchedule[] = [
  {
    scheduleId: "app_deploys_purge",
    workflowType: "DeploysPurgeWorkflow",
    cron: "0 5 * * *",
    timezone: "America/Los_Angeles",
    argsJson: undefined,
    timeout: "30 minutes",
    catchupWindow: undefined,
    source: "feature:deploys",
  },
  {
    scheduleId: "app_felogs_purge",
    workflowType: "FelogsPurgeWorkflow",
    cron: "0 4 * * *",
    timezone: "America/Los_Angeles",
    argsJson: undefined,
    timeout: "30 minutes",
    catchupWindow: undefined,
    source: "feature:felogs",
  },
  {
    scheduleId: "app_guest-wifi_purge",
    workflowType: "GuestWifiPurgeWorkflow",
    cron: "0 2 * * *",
    timezone: "America/Los_Angeles",
    argsJson: undefined,
    timeout: "30 minutes",
    catchupWindow: undefined,
    source: "feature:guest-wifi",
  },
  {
    scheduleId: "app_temporal-health_health-check",
    workflowType: "HealthCheckWorkflow",
    cron: "* * * * *",
    timezone: undefined,
    argsJson: "{\"iterations\":5}",
    timeout: "2 minutes",
    catchupWindow: "1 minute",
    source: "feature:temporal-health",
  },
  {
    scheduleId: "app_weather_purge",
    workflowType: "WeatherPurgeWorkflow",
    cron: "0 3 * * *",
    timezone: "America/Los_Angeles",
    argsJson: undefined,
    timeout: "30 minutes",
    catchupWindow: undefined,
    source: "feature:weather",
  },
];
