// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatcher_state.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dispatcherState = `-- name: DispatcherState :one
SELECT singleton, paused, max_in_flight, breaker_open_until, breaker_reason, in_flight, next_ticket_id, written_at FROM dispatcher_state WHERE singleton = TRUE
`

func (q *Queries) DispatcherState(ctx context.Context) (DispatcherState, error) {
	row := q.db.QueryRow(ctx, dispatcherState)
	var i DispatcherState
	err := row.Scan(
		&i.Singleton,
		&i.Paused,
		&i.MaxInFlight,
		&i.BreakerOpenUntil,
		&i.BreakerReason,
		&i.InFlight,
		&i.NextTicketID,
		&i.WrittenAt,
	)
	return i, err
}

const putDispatcherState = `-- name: PutDispatcherState :exec
UPDATE dispatcher_state
SET paused = $1,
    max_in_flight = $2,
    breaker_open_until = $3,
    breaker_reason = $4,
    in_flight = $5,
    next_ticket_id = $6,
    written_at = $7
WHERE singleton = TRUE
`

type PutDispatcherStateParams struct {
	Paused           bool
	MaxInFlight      int32
	BreakerOpenUntil pgtype.Timestamptz
	BreakerReason    pgtype.Text
	InFlight         []byte
	NextTicketID     pgtype.Int8
	WrittenAt        pgtype.Timestamptz
}

func (q *Queries) PutDispatcherState(ctx context.Context, arg PutDispatcherStateParams) error {
	_, err := q.db.Exec(ctx, putDispatcherState,
		arg.Paused,
		arg.MaxInFlight,
		arg.BreakerOpenUntil,
		arg.BreakerReason,
		arg.InFlight,
		arg.NextTicketID,
		arg.WrittenAt,
	)
	return err
}
