// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const endRun = `-- name: EndRun :one
UPDATE run SET ended_at = $2, outcome = $3, failure_kind = $4
WHERE id = $1
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind
`

type EndRunParams struct {
	ID          pgtype.UUID
	EndedAt     pgtype.Timestamptz
	Outcome     pgtype.Text
	FailureKind string
}

func (q *Queries) EndRun(ctx context.Context, arg EndRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, endRun,
		arg.ID,
		arg.EndedAt,
		arg.Outcome,
		arg.FailureKind,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}

const run = `-- name: Run :one
SELECT id, ticket_id, started_at, ended_at, outcome, failure_kind FROM run WHERE id = $1
`

func (q *Queries) Run(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, run, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}

const startRun = `-- name: StartRun :one
INSERT INTO run (id, ticket_id, started_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    ticket_id = EXCLUDED.ticket_id,
    started_at = EXCLUDED.started_at
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind
`

type StartRunParams struct {
	ID        pgtype.UUID
	TicketID  int64
	StartedAt pgtype.Timestamptz
}

// Idempotent: a retried call starting the same run id again overwrites the
// row with the same values (an activity retry always carries what the first
// attempt did) rather than violating the primary key.
func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, startRun, arg.ID, arg.TicketID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}
