// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_edges.sql

package storedb

import (
	"context"
)

const addTicketDependency = `-- name: AddTicketDependency :exec
INSERT INTO ticket_edge (blocker_ticket_id, blocked_ticket_id)
VALUES ($1, $2)
`

type AddTicketDependencyParams struct {
	BlockerTicketID int64
	BlockedTicketID int64
}

// Cycle rejection is application-level, owned by the API ticket that creates
// edges (ADR-0012) -- this query only records the edge.
func (q *Queries) AddTicketDependency(ctx context.Context, arg AddTicketDependencyParams) error {
	_, err := q.db.Exec(ctx, addTicketDependency, arg.BlockerTicketID, arg.BlockedTicketID)
	return err
}

const removeTicketDependency = `-- name: RemoveTicketDependency :exec
DELETE FROM ticket_edge
WHERE blocker_ticket_id = $1 AND blocked_ticket_id = $2
`

type RemoveTicketDependencyParams struct {
	BlockerTicketID int64
	BlockedTicketID int64
}

func (q *Queries) RemoveTicketDependency(ctx context.Context, arg RemoveTicketDependencyParams) error {
	_, err := q.db.Exec(ctx, removeTicketDependency, arg.BlockerTicketID, arg.BlockedTicketID)
	return err
}

const ticketBlockers = `-- name: TicketBlockers :many
SELECT blocker.id, blocker.title, blocker.body, blocker.state, blocker.created_at, blocker.updated_at FROM ticket_edge e
JOIN ticket blocker ON blocker.id = e.blocker_ticket_id
WHERE e.blocked_ticket_id = $1
ORDER BY blocker.id
`

// Every ticket that blocks the given ticket.
func (q *Queries) TicketBlockers(ctx context.Context, blockedTicketID int64) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, ticketBlockers, blockedTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketBlocks = `-- name: TicketBlocks :many
SELECT blocked.id, blocked.title, blocked.body, blocked.state, blocked.created_at, blocked.updated_at FROM ticket_edge e
JOIN ticket blocked ON blocked.id = e.blocked_ticket_id
WHERE e.blocker_ticket_id = $1
ORDER BY blocked.id
`

// Every ticket the given ticket blocks.
func (q *Queries) TicketBlocks(ctx context.Context, blockerTicketID int64) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, ticketBlocks, blockerTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
