// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcripts.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const putTranscript = `-- name: PutTranscript :exec
INSERT INTO transcript (
    run_id, stage, turn, attempt_no,
    compressed_bytes, compression, uncompressed_size_bytes, checksum
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type PutTranscriptParams struct {
	RunID                 pgtype.UUID
	Stage                 string
	Turn                  int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

func (q *Queries) PutTranscript(ctx context.Context, arg PutTranscriptParams) error {
	_, err := q.db.Exec(ctx, putTranscript,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.CompressedBytes,
		arg.Compression,
		arg.UncompressedSizeBytes,
		arg.Checksum,
	)
	return err
}

const transcript = `-- name: Transcript :one
SELECT run_id, stage, turn, attempt_no, compressed_bytes, compression, uncompressed_size_bytes, checksum FROM transcript
WHERE run_id = $1 AND stage = $2 AND turn = $3 AND attempt_no = $4
`

type TranscriptParams struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	AttemptNo int32
}

func (q *Queries) Transcript(ctx context.Context, arg TranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, transcript,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
	)
	var i Transcript
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.CompressedBytes,
		&i.Compression,
		&i.UncompressedSizeBytes,
		&i.Checksum,
	)
	return i, err
}
