// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v0.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTargetTicket = `-- name: ActivateTargetTicket :one
UPDATE ticket SET state = 'active', active_run_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'open'
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type ActivateTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) ActivateTargetTicket(ctx context.Context, arg ActivateTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, activateTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const checkpointTargetAgentAttempt = `-- name: CheckpointTargetAgentAttempt :one
UPDATE run_agent_attempt SET
    provider_thread_id = $4,
    state = $5,
    failure_kind = $6,
    usage_state = $7,
    input_tokens = $8,
    cached_input_tokens = $9,
    output_tokens = $10,
    reasoning_tokens = $11,
    ended_at = $12,
    result = $13
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3
RETURNING run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, provider_thread_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result
`

type CheckpointTargetAgentAttemptParams struct {
	RunID             pgtype.UUID
	StepOrdinal       int32
	AttemptNo         int32
	ProviderThreadID  string
	State             string
	FailureKind       string
	UsageState        string
	InputTokens       int64
	CachedInputTokens int64
	OutputTokens      int64
	ReasoningTokens   int64
	EndedAt           pgtype.Timestamptz
	Result            []byte
}

func (q *Queries) CheckpointTargetAgentAttempt(ctx context.Context, arg CheckpointTargetAgentAttemptParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, checkpointTargetAgentAttempt,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.ProviderThreadID,
		arg.State,
		arg.FailureKind,
		arg.UsageState,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.EndedAt,
		arg.Result,
	)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ProviderThreadID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const completeTargetRunCanceled = `-- name: CompleteTargetRunCanceled :one
UPDATE run SET target_outcome = 'canceled', target_failure_kind = '', ended_at = $2
WHERE id = $1 AND target_outcome IS NULL
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha, checkpoint_capability_hash
`

type CompleteTargetRunCanceledParams struct {
	ID      pgtype.UUID
	EndedAt pgtype.Timestamptz
}

func (q *Queries) CompleteTargetRunCanceled(ctx context.Context, arg CompleteTargetRunCanceledParams) (Run, error) {
	row := q.db.QueryRow(ctx, completeTargetRunCanceled, arg.ID, arg.EndedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const completeTargetRunSuccess = `-- name: CompleteTargetRunSuccess :one
UPDATE run SET target_outcome = 'succeeded', target_failure_kind = '',
    reviewed_head = $2, merge_sha = $3, ended_at = $4
WHERE id = $1 AND target_outcome IS NULL
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha, checkpoint_capability_hash
`

type CompleteTargetRunSuccessParams struct {
	ID           pgtype.UUID
	ReviewedHead pgtype.Text
	MergeSha     pgtype.Text
	EndedAt      pgtype.Timestamptz
}

func (q *Queries) CompleteTargetRunSuccess(ctx context.Context, arg CompleteTargetRunSuccessParams) (Run, error) {
	row := q.db.QueryRow(ctx, completeTargetRunSuccess,
		arg.ID,
		arg.ReviewedHead,
		arg.MergeSha,
		arg.EndedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const completeTargetStep = `-- name: CompleteTargetStep :one
UPDATE run_step SET state = 'completed', ended_at = $3, result = $4
WHERE run_id = $1 AND ordinal = $2
  AND (state = 'running' OR (state = 'completed' AND result = $4))
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type CompleteTargetStepParams struct {
	RunID   pgtype.UUID
	Ordinal int32
	EndedAt pgtype.Timestamptz
	Result  []byte
}

func (q *Queries) CompleteTargetStep(ctx context.Context, arg CompleteTargetStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, completeTargetStep,
		arg.RunID,
		arg.Ordinal,
		arg.EndedAt,
		arg.Result,
	)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const completeTargetTicket = `-- name: CompleteTargetTicket :one
UPDATE ticket SET state = 'done', active_run_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'active' AND active_run_id = $2
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type CompleteTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) CompleteTargetTicket(ctx context.Context, arg CompleteTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, completeTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const insertTargetRun = `-- name: InsertTargetRun :one
INSERT INTO run (id, ticket_id, started_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET id = run.id
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha, checkpoint_capability_hash
`

type InsertTargetRunParams struct {
	ID        pgtype.UUID
	TicketID  int64
	StartedAt pgtype.Timestamptz
}

func (q *Queries) InsertTargetRun(ctx context.Context, arg InsertTargetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, insertTargetRun, arg.ID, arg.TicketID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const putTargetAgentTranscript = `-- name: PutTargetAgentTranscript :exec
INSERT INTO run_agent_transcript (
    run_id, step_ordinal, attempt_no, compressed_bytes, compression,
    uncompressed_size_bytes, checksum
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (run_id, step_ordinal, attempt_no) DO NOTHING
`

type PutTargetAgentTranscriptParams struct {
	RunID                 pgtype.UUID
	StepOrdinal           int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

func (q *Queries) PutTargetAgentTranscript(ctx context.Context, arg PutTargetAgentTranscriptParams) error {
	_, err := q.db.Exec(ctx, putTargetAgentTranscript,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.CompressedBytes,
		arg.Compression,
		arg.UncompressedSizeBytes,
		arg.Checksum,
	)
	return err
}

const putTargetGitCheckpoint = `-- name: PutTargetGitCheckpoint :one
INSERT INTO run_git_checkpoint (
    run_id, step_ordinal, branch, pushed_head, observed_base,
    pull_request_number, pull_request_node_id, step_result
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (run_id) DO UPDATE SET
    step_ordinal = EXCLUDED.step_ordinal,
    branch = EXCLUDED.branch,
    pushed_head = EXCLUDED.pushed_head,
    observed_base = EXCLUDED.observed_base,
    pull_request_number = EXCLUDED.pull_request_number,
    pull_request_node_id = EXCLUDED.pull_request_node_id,
    step_result = EXCLUDED.step_result
WHERE run_git_checkpoint.step_ordinal <= EXCLUDED.step_ordinal
RETURNING run_id, step_ordinal, branch, pushed_head, observed_base, pull_request_number, pull_request_node_id, step_result
`

type PutTargetGitCheckpointParams struct {
	RunID             pgtype.UUID
	StepOrdinal       int32
	Branch            string
	PushedHead        string
	ObservedBase      string
	PullRequestNumber int32
	PullRequestNodeID string
	StepResult        []byte
}

func (q *Queries) PutTargetGitCheckpoint(ctx context.Context, arg PutTargetGitCheckpointParams) (RunGitCheckpoint, error) {
	row := q.db.QueryRow(ctx, putTargetGitCheckpoint,
		arg.RunID,
		arg.StepOrdinal,
		arg.Branch,
		arg.PushedHead,
		arg.ObservedBase,
		arg.PullRequestNumber,
		arg.PullRequestNodeID,
		arg.StepResult,
	)
	var i RunGitCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.Branch,
		&i.PushedHead,
		&i.ObservedBase,
		&i.PullRequestNumber,
		&i.PullRequestNodeID,
		&i.StepResult,
	)
	return i, err
}

const reopenTargetTicket = `-- name: ReopenTargetTicket :one
UPDATE ticket SET state = 'open', active_run_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'active' AND active_run_id = $2
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type ReopenTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) ReopenTargetTicket(ctx context.Context, arg ReopenTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, reopenTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const setRunCheckpointCapabilityHash = `-- name: SetRunCheckpointCapabilityHash :exec
UPDATE run SET checkpoint_capability_hash = $2 WHERE id = $1
`

type SetRunCheckpointCapabilityHashParams struct {
	ID                       pgtype.UUID
	CheckpointCapabilityHash pgtype.Text
}

func (q *Queries) SetRunCheckpointCapabilityHash(ctx context.Context, arg SetRunCheckpointCapabilityHashParams) error {
	_, err := q.db.Exec(ctx, setRunCheckpointCapabilityHash, arg.ID, arg.CheckpointCapabilityHash)
	return err
}

const startTargetAgentAttempt = `-- name: StartTargetAgentAttempt :one
INSERT INTO run_agent_attempt (
    run_id, step_ordinal, attempt_no, agent_stage, model, effort, state,
    usage_state, started_at
) VALUES ($1, $2, $3, $4, $5, $6, 'running', $7, $8)
ON CONFLICT (run_id, step_ordinal, attempt_no) DO UPDATE SET run_id = run_agent_attempt.run_id
RETURNING run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, provider_thread_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result
`

type StartTargetAgentAttemptParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
	AgentStage  string
	Model       string
	Effort      string
	UsageState  string
	StartedAt   pgtype.Timestamptz
}

func (q *Queries) StartTargetAgentAttempt(ctx context.Context, arg StartTargetAgentAttemptParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, startTargetAgentAttempt,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.AgentStage,
		arg.Model,
		arg.Effort,
		arg.UsageState,
		arg.StartedAt,
	)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ProviderThreadID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const startTargetStep = `-- name: StartTargetStep :one
INSERT INTO run_step (run_id, ordinal, kind, iteration, reason, state, started_at)
VALUES ($1, $2, $3, $4, $5, 'running', $6)
ON CONFLICT (run_id, ordinal) DO UPDATE SET run_id = run_step.run_id
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type StartTargetStepParams struct {
	RunID     pgtype.UUID
	Ordinal   int32
	Kind      string
	Iteration int32
	Reason    string
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartTargetStep(ctx context.Context, arg StartTargetStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, startTargetStep,
		arg.RunID,
		arg.Ordinal,
		arg.Kind,
		arg.Iteration,
		arg.Reason,
		arg.StartedAt,
	)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const targetAgentAttemptForUpdate = `-- name: TargetAgentAttemptForUpdate :one
SELECT run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, provider_thread_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result FROM run_agent_attempt
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3 FOR UPDATE
`

type TargetAgentAttemptForUpdateParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
}

func (q *Queries) TargetAgentAttemptForUpdate(ctx context.Context, arg TargetAgentAttemptForUpdateParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, targetAgentAttemptForUpdate, arg.RunID, arg.StepOrdinal, arg.AttemptNo)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ProviderThreadID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const targetAgentAttemptsForRun = `-- name: TargetAgentAttemptsForRun :many
SELECT run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, provider_thread_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result FROM run_agent_attempt WHERE run_id = $1 ORDER BY step_ordinal, attempt_no
`

func (q *Queries) TargetAgentAttemptsForRun(ctx context.Context, runID pgtype.UUID) ([]RunAgentAttempt, error) {
	rows, err := q.db.Query(ctx, targetAgentAttemptsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunAgentAttempt
	for rows.Next() {
		var i RunAgentAttempt
		if err := rows.Scan(
			&i.RunID,
			&i.StepOrdinal,
			&i.AttemptNo,
			&i.AgentStage,
			&i.Model,
			&i.Effort,
			&i.State,
			&i.FailureKind,
			&i.ProviderThreadID,
			&i.UsageState,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetGitCheckpoint = `-- name: TargetGitCheckpoint :one
SELECT run_id, step_ordinal, branch, pushed_head, observed_base, pull_request_number, pull_request_node_id, step_result FROM run_git_checkpoint WHERE run_id = $1
`

func (q *Queries) TargetGitCheckpoint(ctx context.Context, runID pgtype.UUID) (RunGitCheckpoint, error) {
	row := q.db.QueryRow(ctx, targetGitCheckpoint, runID)
	var i RunGitCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.Branch,
		&i.PushedHead,
		&i.ObservedBase,
		&i.PullRequestNumber,
		&i.PullRequestNodeID,
		&i.StepResult,
	)
	return i, err
}

const targetRunForUpdate = `-- name: TargetRunForUpdate :one
SELECT id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha, checkpoint_capability_hash FROM run WHERE id = $1 FOR UPDATE
`

func (q *Queries) TargetRunForUpdate(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, targetRunForUpdate, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const targetStepForRun = `-- name: TargetStepForRun :many
SELECT run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result FROM run_step WHERE run_id = $1 ORDER BY ordinal
`

func (q *Queries) TargetStepForRun(ctx context.Context, runID pgtype.UUID) ([]RunStep, error) {
	rows, err := q.db.Query(ctx, targetStepForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Ordinal,
			&i.Kind,
			&i.Iteration,
			&i.Reason,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetTicketForUpdate = `-- name: TargetTicketForUpdate :one
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket WHERE id = $1 FOR UPDATE
`

func (q *Queries) TargetTicketForUpdate(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, targetTicketForUpdate, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const targetTranscriptKeysForRun = `-- name: TargetTranscriptKeysForRun :many
SELECT run_id, step_ordinal, attempt_no FROM run_agent_transcript
WHERE run_id = $1 ORDER BY step_ordinal, attempt_no
`

type TargetTranscriptKeysForRunRow struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
}

func (q *Queries) TargetTranscriptKeysForRun(ctx context.Context, runID pgtype.UUID) ([]TargetTranscriptKeysForRunRow, error) {
	rows, err := q.db.Query(ctx, targetTranscriptKeysForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetTranscriptKeysForRunRow
	for rows.Next() {
		var i TargetTranscriptKeysForRunRow
		if err := rows.Scan(&i.RunID, &i.StepOrdinal, &i.AttemptNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketForTargetClaim = `-- name: TicketForTargetClaim :one
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket WHERE id = $1 FOR UPDATE
`

func (q *Queries) TicketForTargetClaim(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketForTargetClaim, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}
