// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDependency = `-- name: AddDependency :exec
INSERT INTO ticket_edge (blocker_ticket_id, blocked_ticket_id) VALUES ($1, $2)
`

type AddDependencyParams struct {
	BlockerTicketID int64
	BlockedTicketID int64
}

func (q *Queries) AddDependency(ctx context.Context, arg AddDependencyParams) error {
	_, err := q.db.Exec(ctx, addDependency, arg.BlockerTicketID, arg.BlockedTicketID)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO ticket (title, body, state) VALUES ($1, $2, $3) RETURNING id, title, body, state, created_at, updated_at
`

type CreateTicketParams struct {
	Title string
	Body  string
	State string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.Title, arg.Body, arg.State)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endAttempt = `-- name: EndAttempt :one
UPDATE attempt SET ended_at = $5, result = $6, input_tokens = $7, cached_input_tokens = $8, output_tokens = $9, reasoning_tokens = $10, measured = $11
WHERE run_id = $1 AND stage = $2 AND turn = $3 AND attempt_no = $4 RETURNING run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result
`

type EndAttemptParams struct {
	RunID             pgtype.UUID
	Stage             string
	Turn              int32
	AttemptNo         int32
	EndedAt           pgtype.Timestamptz
	Result            pgtype.Text
	InputTokens       int64
	CachedInputTokens int64
	OutputTokens      int64
	ReasoningTokens   int64
	Measured          bool
}

func (q *Queries) EndAttempt(ctx context.Context, arg EndAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, endAttempt,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.EndedAt,
		arg.Result,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.Measured,
	)
	var i Attempt
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.Model,
		&i.Effort,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.Measured,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const endRun = `-- name: EndRun :one
UPDATE run SET ended_at = $2, outcome = $3, failure_kind = $4 WHERE id = $1 RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind
`

type EndRunParams struct {
	ID          pgtype.UUID
	EndedAt     pgtype.Timestamptz
	Outcome     pgtype.Text
	FailureKind string
}

func (q *Queries) EndRun(ctx context.Context, arg EndRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, endRun,
		arg.ID,
		arg.EndedAt,
		arg.Outcome,
		arg.FailureKind,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}

const getDispatcherState = `-- name: GetDispatcherState :one
SELECT singleton, paused, max_in_flight, breaker_open_until, breaker_reason, in_flight, next_ticket_id, written_at FROM dispatcher_state WHERE singleton = TRUE
`

func (q *Queries) GetDispatcherState(ctx context.Context) (DispatcherState, error) {
	row := q.db.QueryRow(ctx, getDispatcherState)
	var i DispatcherState
	err := row.Scan(
		&i.Singleton,
		&i.Paused,
		&i.MaxInFlight,
		&i.BreakerOpenUntil,
		&i.BreakerReason,
		&i.InFlight,
		&i.NextTicketID,
		&i.WrittenAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, ticket_id, started_at, ended_at, outcome, failure_kind FROM run WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, title, body, state, created_at, updated_at FROM ticket WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscript = `-- name: GetTranscript :one
SELECT run_id, stage, turn, attempt_no, compressed_bytes, compression, uncompressed_size_bytes, checksum FROM transcript WHERE run_id = $1 AND stage = $2 AND turn = $3 AND attempt_no = $4
`

type GetTranscriptParams struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	AttemptNo int32
}

func (q *Queries) GetTranscript(ctx context.Context, arg GetTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscript,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
	)
	var i Transcript
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.CompressedBytes,
		&i.Compression,
		&i.UncompressedSizeBytes,
		&i.Checksum,
	)
	return i, err
}

const listReadyTickets = `-- name: ListReadyTickets :many
SELECT t.id, t.title, t.body, t.state, t.created_at, t.updated_at FROM ticket t WHERE t.state = 'open' AND NOT EXISTS (
  SELECT 1 FROM ticket_edge e JOIN ticket blocker ON blocker.id = e.blocker_ticket_id
  WHERE e.blocked_ticket_id = t.id AND blocker.state <> 'done'
) ORDER BY t.created_at, t.id
`

func (q *Queries) ListReadyTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listReadyTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunAttempts = `-- name: ListRunAttempts :many
SELECT run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result FROM attempt WHERE run_id = $1 ORDER BY stage, turn, attempt_no
`

func (q *Queries) ListRunAttempts(ctx context.Context, runID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listRunAttempts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.RunID,
			&i.Stage,
			&i.Turn,
			&i.AttemptNo,
			&i.Model,
			&i.Effort,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.Measured,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT run_id, stage, turn FROM step WHERE run_id = $1 ORDER BY stage, turn
`

func (q *Queries) ListRunSteps(ctx context.Context, runID pgtype.UUID) ([]Step, error) {
	rows, err := q.db.Query(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(&i.RunID, &i.Stage, &i.Turn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketBlockers = `-- name: ListTicketBlockers :many
SELECT t.id, t.title, t.body, t.state, t.created_at, t.updated_at FROM ticket t JOIN ticket_edge e ON e.blocker_ticket_id = t.id WHERE e.blocked_ticket_id = $1 ORDER BY t.id
`

func (q *Queries) ListTicketBlockers(ctx context.Context, blockedTicketID int64) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketBlockers, blockedTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsBlockedBy = `-- name: ListTicketsBlockedBy :many
SELECT t.id, t.title, t.body, t.state, t.created_at, t.updated_at FROM ticket t JOIN ticket_edge e ON e.blocked_ticket_id = t.id WHERE e.blocker_ticket_id = $1 ORDER BY t.id
`

func (q *Queries) ListTicketsBlockedBy(ctx context.Context, blockerTicketID int64) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsBlockedBy, blockerTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByState = `-- name: ListTicketsByState :many
SELECT id, title, body, state, created_at, updated_at FROM ticket WHERE state = $1 ORDER BY created_at, id
`

func (q *Queries) ListTicketsByState(ctx context.Context, state string) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStep = `-- name: RecordStep :one
INSERT INTO step (run_id, stage, turn) VALUES ($1, $2, $3) RETURNING run_id, stage, turn
`

type RecordStepParams struct {
	RunID pgtype.UUID
	Stage string
	Turn  int32
}

func (q *Queries) RecordStep(ctx context.Context, arg RecordStepParams) (Step, error) {
	row := q.db.QueryRow(ctx, recordStep, arg.RunID, arg.Stage, arg.Turn)
	var i Step
	err := row.Scan(&i.RunID, &i.Stage, &i.Turn)
	return i, err
}

const removeDependency = `-- name: RemoveDependency :exec
DELETE FROM ticket_edge WHERE blocker_ticket_id = $1 AND blocked_ticket_id = $2
`

type RemoveDependencyParams struct {
	BlockerTicketID int64
	BlockedTicketID int64
}

func (q *Queries) RemoveDependency(ctx context.Context, arg RemoveDependencyParams) error {
	_, err := q.db.Exec(ctx, removeDependency, arg.BlockerTicketID, arg.BlockedTicketID)
	return err
}

const setDispatcherState = `-- name: SetDispatcherState :one
UPDATE dispatcher_state SET paused = $1, max_in_flight = $2, breaker_open_until = $3, breaker_reason = $4, in_flight = $5, next_ticket_id = $6, written_at = $7 WHERE singleton = TRUE RETURNING singleton, paused, max_in_flight, breaker_open_until, breaker_reason, in_flight, next_ticket_id, written_at
`

type SetDispatcherStateParams struct {
	Paused           bool
	MaxInFlight      int32
	BreakerOpenUntil pgtype.Timestamptz
	BreakerReason    pgtype.Text
	InFlight         []byte
	NextTicketID     pgtype.Int8
	WrittenAt        pgtype.Timestamptz
}

func (q *Queries) SetDispatcherState(ctx context.Context, arg SetDispatcherStateParams) (DispatcherState, error) {
	row := q.db.QueryRow(ctx, setDispatcherState,
		arg.Paused,
		arg.MaxInFlight,
		arg.BreakerOpenUntil,
		arg.BreakerReason,
		arg.InFlight,
		arg.NextTicketID,
		arg.WrittenAt,
	)
	var i DispatcherState
	err := row.Scan(
		&i.Singleton,
		&i.Paused,
		&i.MaxInFlight,
		&i.BreakerOpenUntil,
		&i.BreakerReason,
		&i.InFlight,
		&i.NextTicketID,
		&i.WrittenAt,
	)
	return i, err
}

const setTicketState = `-- name: SetTicketState :one
UPDATE ticket SET state = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, title, body, state, created_at, updated_at
`

type SetTicketStateParams struct {
	ID    int64
	State string
}

func (q *Queries) SetTicketState(ctx context.Context, arg SetTicketStateParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, setTicketState, arg.ID, arg.State)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startAttempt = `-- name: StartAttempt :one
INSERT INTO attempt (run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at)
VALUES ($1, $2, $3, $4, $5, $6, 0, 0, 0, 0, FALSE, $7) RETURNING run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result
`

type StartAttemptParams struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	AttemptNo int32
	Model     string
	Effort    string
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartAttempt(ctx context.Context, arg StartAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, startAttempt,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.Model,
		arg.Effort,
		arg.StartedAt,
	)
	var i Attempt
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.Model,
		&i.Effort,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.Measured,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const startRun = `-- name: StartRun :one
INSERT INTO run (id, ticket_id, started_at) VALUES ($1, $2, $3) RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind
`

type StartRunParams struct {
	ID        pgtype.UUID
	TicketID  int64
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, startRun, arg.ID, arg.TicketID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}

const upsertTranscript = `-- name: UpsertTranscript :one
INSERT INTO transcript (run_id, stage, turn, attempt_no, compressed_bytes, compression, uncompressed_size_bytes, checksum)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (run_id, stage, turn, attempt_no) DO UPDATE SET compressed_bytes = EXCLUDED.compressed_bytes, compression = EXCLUDED.compression, uncompressed_size_bytes = EXCLUDED.uncompressed_size_bytes, checksum = EXCLUDED.checksum
RETURNING run_id, stage, turn, attempt_no, compressed_bytes, compression, uncompressed_size_bytes, checksum
`

type UpsertTranscriptParams struct {
	RunID                 pgtype.UUID
	Stage                 string
	Turn                  int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

func (q *Queries) UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, upsertTranscript,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.CompressedBytes,
		arg.Compression,
		arg.UncompressedSizeBytes,
		arg.Checksum,
	)
	var i Transcript
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.CompressedBytes,
		&i.Compression,
		&i.UncompressedSizeBytes,
		&i.Checksum,
	)
	return i, err
}
